### ISSUE TITLE
Do you have a concurrentdictionary that will update the WPF UI real time?

### ISSUE THREAD

**Issue by heavywoody** [meziantou/Meziantou.Framework#228]
I am testing your ConcurrentObservableCollection, which is fantastic!  But what I run into is think of a stock market.  I have a key field thats value never changes.  But what changes is the other three properties.  So I thought of creating a ConcurrentDictionary making the key be in stockID and then the value would be an object with the other three properties.  The issue I am having now is everytime a stock notification change comes in, I have to check if it exists in the ConcurrentObservableCollection and then add it or update it, which is taking too long for my application.  Unless I am not using it correctly. I thought maybe using a dictionary key would speed that up.

I typical piece of data I have might be:

Stock#    OldValue  NewValue  Status.  And then I would look up the Stock# like a dictionary. Any thoughts?

**Comment by meziantou** [comment]
The ConcurrentObservableCollection does not provide a way find an element by a key and it is not something that could be added easily. That's being said, there are multiple ways to handle your case:
- If the data are sorted by StockId, you can find existing items using a binary search
- Add a dictionary<StockId, index in the collection> but this increases the complexity
- Write your own collection that matches your needs

note: before adding such complexity, you should validate that the issue is actually searching data in the collection by measuring using a Stopwatch or BenchmarkDotnet

**Comment by heavywoody** [comment]
Thanks!
