### ISSUE TITLE
REquest

### ISSUE THREAD

**Issue by musaffar-patel** [meziantou/Meziantou.Framework#481]
Could you expand the DataGrid tutorial to include sorting functions for each of the columns and associated data?  For those of us who arrived at this component via your online tutorial it would be a great way to introduce us to Events and passing events between components.  I have attempted this myself  but have made little progress.

**Comment by meziantou** [comment]
Sorry, I won't spend time to improve the samples of the DataGrid component. Since the component was created, MS has created a Grid component that provides similar features. You can use their component if you want a better support and samples:

- [Experimental QuickGrid component for Blazor](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-6/?WT.mc_id=DT-MVP-5003978#experimental-quickgrid-component-for-blazor)
- https://aspnet.github.io/quickgridsamples/getstarted
