### ISSUE TITLE
CredentialManager in VS2022 projects

### ISSUE THREAD

**Issue by gitkrasty** [meziantou/Meziantou.Framework#504]
Dear Author, 
we have historically used the Meziantou.*.CredentialManager, and now we would like to update our old project to follow the nugget version. But in the nugget repo it is quite outdated and only with NET5 mentioned. And our project refuses to use this version as the DLL can not be loaded (it complains that it is not strongly named). 

I have also discovered, that the CredentialManager is part of source codes for Meziantou.Framework, where it has been somehow amended for NET7, but it seems that this source of credential manager folder is not compiled into the Meziantou.Framework Version:3.0.28 nugget. Is this by design and I have missed something?

 Or could you please help me understand how to use this functionality in our VS2022 projects for .NET Framework 4.7.1 and/or NET7 ?

![image](https://user-images.githubusercontent.com/52275670/208423598-16e28140-9ac8-4d70-8f71-9c774709a82d.png)

**Comment by meziantou** [comment]
The CredentialManager project has not been significantly changed since the package was published. No new features, no bug fix. The code was updated to fix analyzer warnings, use newer C# syntax, or update TFM. So, there is no reason to publish a new package.

If you want you can checkout the commit of the package. You can get the SHA1 by using [NuGet Package Explorer](https://nuget.info/packages/Meziantou.Framework.Win32.CredentialManager/1.4.2):

<img width="625" alt="image" src="https://user-images.githubusercontent.com/509220/208447466-5af8f8d1-4307-4355-9f85-1ec0e9b9d0aa.png">

> it complains that it is not strongly named

See https://github.com/meziantou/Meziantou.Framework/issues/487 for more details
