### ISSUE TITLE
How to access a GitHub private repo?

### ISSUE THREAD

**Issue by bm-ifarkas** [meziantou/Meziantou.Framework#563]
# How to access a GitHub private repo?

## private repo repo
`https://github.com/Owner/Repo` _(valid link, visible when logged in to GitHub)_

**CLI**
```shell
meziantou.validate-nuget-package "src\bin\Release\Repo.1.0.0.nupkg"
```

**Response**
```json
{
  "ErrorCode": 52,
  "Message": "Project url \u0027https://github.com/Owner/Repo\u0027 is not accessible"
}
```

**Comment by meziantou** [comment]
If you use the library, you can set `NuGetPackageValidationOptions.ConfigureRequest` to add authentication.

If you use the dotnet tool, you can use the `--github-token` option.

**Comment by meziantou** [comment]
The issue is that you cannot authenticate the request to a `https://github.com` using a token. You need to use a cookie. Only `api.github.com` and `raw.githubusercontent.com` can be authenticated using the token. That's why the provided token is only used to validate the files from the symbols are accessible, but not the project url.

So, this rule cannot be used with private GitHub repositories. You can disable it using `--excluded-rule-ids 52`

**Comment by bm-ifarkas** [comment]
Thx so much.
